version: '3'
services:
  master:
    image: taherbs/locust
    container_name: locustmaster
    ports:
      - 5557-5558:5557-5558
      - 8089:8089
    volumes:
      - ./locust-tasks:/locust
    env_file:
      - .env
    environment:
      - LOCUST_MODE=master
    networks:
      - locustnetwork

  slave1:
    image: taherbs/locust
    container_name: locustslave1
    depends_on:
      - master
    volumes:
      - ./locust-tasks:/locust
    env_file:
      - .env
    environment:
      - LOCUST_MODE=slave
      - LOCUST_MASTER=master
    networks:
      - locustnetwork

  slave2:
    image: taherbs/locust
    container_name: locustslave2
    depends_on:
      - master
    volumes:
      - ./locust-tasks:/locust
    env_file:
      - .env
    environment:
      - LOCUST_MODE=slave
      - LOCUST_MASTER=master
    networks:
      - locustnetwork
### Networks Setup ###
networks:
  locustnetwork:
    driver: "bridge"
